### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by ChrisZeThird** [LupaDevStudio/Geozzle#4]
Here is the traceback:

```
Traceback (most recent call last):
   File "C:\Users\wilan\PycharmProjects\Geozzle\main.py", line 209, in <module>
     MainApp().run()
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\wilan\PycharmProjects\Geozzle\venv\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\wilan\PycharmProjects\Geozzle\screens\opening.py", line 94, in load_other_screens
     game_over_screen = self.GameOverScreen(name="game_over")
   File "C:\Users\wilan\PycharmProjects\Geozzle\screens\game_over.py", line 67, in __init__
     self.update_text()
   File "C:\Users\wilan\PycharmProjects\Geozzle\screens\game_over.py", line 115, in update_text
     self.validate_label = TEXT.game_over["validate"]
 KeyError: 'validate'
```

**Comment by LupaDevStudio** [comment]
Thanks for your issue, unfortunately the game is not finished yet and the back end of the application has not been linked with the front end yet and the game cannot be played. I will close the issue as the code of the app will still evolve a lot in the next weeks. The application should according to our plans be completed before the 25th February. It might be playable before but we can guarantee it.
